name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
        required: true
        description: Provide the Ingress URL
        type: string
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl https://${{ inputs.ingress-url }}/live -s -k | jq -r .status | grep -i live
