name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
        required: true
        description: Provide the Ingress URL
        type: string
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.ingress-url }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
